sudo: required
dist: trusty

language: cpp

branches:
  only:
    - master
    - travis_test

notifications:
    on_failure: never
    on_success: never

matrix:
    include:
        - compiler: gcc
          addons:
            apt:
             packages:
               - libboost-all-dev
               - g++-5
               - gcc-5
             sources:
               - ubuntu-toolchain-r-test
          # use compiler which has c++14 support
          env: COMPILER=g++-5

#        - compiler: clang
#          addons:
#            apt:
#             packages:
#               - clang-3.6
#             sources:
#               - ubuntu-toolchain-r-test
#               - llvm-toolchain-precise-3.6
#          # use compiler which has c++14 support
#          env: COMPILER=clang++-3.6

before_install:
    # setup Qt 5.5 which is not in Ubuntu by default. To be removed in the future.
  - sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y
  - sudo apt-get -qq update
  - sudo sudo apt-get install -qq qt55base qt55svg
  - source /opt/qt55/bin/qt55-env.sh

before_script:
  - mkdir build && cd build
  - CXX=$COMPILER cmake  ..

script:
  - make
